# Generated by Django 6.0.1 on 2026-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('request_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('request_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
                ('from_library', models.CharField(max_length=100)),
                ('to_library', models.CharField(max_length=100)),
                ('status', models.CharField(default='Not Approved', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('request_id', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
                ('date_borrowed', models.IntegerField()),
                ('date_returned', models.IntegerField()),
                ('paid_status', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('history', models.TextField(default='None')),
            ],
        ),
    ]
